version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    environment:
      - NODE_ENV=production
      
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your_secure_jwt_secret}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL}
      - JINA_API_KEY=${JINA_API_KEY}